### ISSUE TITLE
cabal install fails

### ISSUE THREAD

**Issue by ghost** [fumieval/webauthn#2]
Its working with stack now, but using cabal install on a fresh clone with latest cabal and ghc fails when attempting to install cryptonite

**Comment by fumieval** [comment]
Care to add details? It's hard to tell what exactly is wrong without looking at concrete failures. I suppose you mean the latest stable releases (GHC 8.10.1 and cabal-install 3.2.0.0)?
If it fails when you are attempting to build cryptonite, it's an issue with cryptonite, not this package's.

**Comment by ghost** [comment]
That's right on versions. Makes sense. I will just use stack for now.
