### ISSUE TITLE
Fix the Android fmt test (and maybe introducing some generic registration/verification data param)

### ISSUE THREAD

**Issue by kubek2k** [fumieval/webauthn#9]
It appears that the certificate that was used to generate the android test has expired and therefore the test is now failing. I would suggest adding a param representing current time (maybe a `Maybe`?). This also make me realize that we observe an explosion of params passed to `register..`/`verify` functions. What do you think about adding a config param that would represent the constant part of usual use of those (that would contain pubkeycredential options, relying party configuration and those)?

**Comment by sumo** [comment]
Hi, I've created a pull request that fixes this and adds a few data types. It is a temporary fix where now is passed into to register. I am happy to move all of this into a proper constant configuration if required so let me know if this is a priority

**Comment by fumieval** [comment]
Fixed in #21
